
stages:
  - containers
  - builds
  - sanity_checks
  - pages

.native_git_build_job:
  extends:
    - .gitlab_native_build_job
  script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
    - export SCRATCH_DIR="/tmp/scratch"
    - export VROOT="$SCRATCH_DIR/vroot"
    - export LIBDIR="$VROOT/lib"
    - export LD_LIBRARY_PATH="$LIBDIR"
    - export PATH="$VROOT/bin:$PATH"
    - export PKG_CONFIG_PATH="$LIBDIR/pkgconfig"
    - pushd "$PWD"
    - mkdir -p "$SCRATCH_DIR"
    - cd "$SCRATCH_DIR"
    - git clone --depth 1 https://gitlab.com/libvirt/libvirt.git
    - cd libvirt
    - meson build -Ddriver_libvirtd=disabled "--prefix=$VROOT" "--libdir=$LIBDIR"
    - ninja -C build install
    - popd
    - autoreconf -i -f
    - ./configure
    - $MAKE
    - $MAKE dist
    - $MAKE maintainer-check-extra-dist

.native_build_job:
  extends:
    - .gitlab_native_build_job
  script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
    - autoreconf -i -f
    - ./configure
    - $MAKE
    - $MAKE dist
    - $MAKE maintainer-check-extra-dist

website:
  extends:
    - .gitlab_native_build_job
  script:
    - export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
    - autoreconf -i -f
    - ./configure
    - $MAKE doc
    - mv html web/
  artifacts:
    paths:
      - public
  variables:
    NAME: ubuntu-2204
    TARGET_BASE_IMAGE: docker.io/library/ubuntu:22.04

pages:
  stage: pages
  dependencies:
    - website
  script:
    - mv web public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_PROJECT_NAMESPACE == $RUN_UPSTREAM_NAMESPACE && $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: on_success
    - when: never

include: '/ci/gitlab.yml'
